name: Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GHCR
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build & Push Backend
      run: |
        docker build -f infra/docker/backend.Dockerfile -t ghcr.io/${{ secrets.GHCR_USERNAME }}/apps-backend:latest ./backend
        docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/apps-backend:latest

    - name: Build & Push Frontend
      run: |
        docker build -f infra/docker/frontend.Dockerfile -t ghcr.io/${{ secrets.GHCR_USERNAME }}/apps-frontend:latest ./frontend
        docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/apps-frontend:latest

    - name: 🚀 Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~
          if [ ! -d "apps" ]; then
            git clone https://github.com/${{ github.repository }} apps
          fi
          cd apps
          git pull origin main
          export GHCR_USERNAME=${{ secrets.GHCR_USERNAME }}
          export GHCR_TOKEN=${{ secrets.GHCR_TOKEN }}
          bash infra/scripts/deploy.sh
