name: Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build backend image
      run: docker build -f infra/docker/backend.Dockerfile -t backend ./apps/backend

    # - name: Build frontend image
    #   run: docker build -f infra/docker/frontend.Dockerfile -t frontend ./apps/frontend